---
- hosts: localhost
  tasks:
    - name: example ec2 group
      ec2_group:
        name: dbsg
        description: an example EC2 group
        vpc_id: vpc-02f3b02af166585a6
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0
      register: dbsg
    - debug:
        var: dbsg
    - rds_subnet_group:
        state: present
        region: us-east-1
        name: dbsubnet
        description: My Fancy Ex Parrot Subnet Group
        subnets:
          - subnet-0c5ce63413d915be1
          - subnet-05c97d9aa1083a47f
      register: dbsubnet
    - debug:
        var: dbsubnet
    - rds:
        command: create
        region: us-east-1
        instance_name: myapp-database
        db_name: userdb
        db_engine: MySQL
        size: 10
        instance_type: db.t2.micro
        username: mysql_admin
        password: 1nsecure
        subnet: dbsubnet
        license_model: "general-public-license"
        vpc_security_groups: "{{ dbsg.group_id }}"
        multi_zone: no
        wait: yes
        wait_timeout: 900
      register: mydb
    - debug:
        var: mydb
    - replace:
        path: ../feandbe/threetier.yaml
        regexp: 'DATABASENAME'
        replace: "{{ mydb.instance.endpoint }}"
        backup: yes
